spring:
  datasource:
    druid:
      driver-class-name:
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/intelligence-locker


server:
  port: 80

mybatis:
#  configuration-properties:
#    offsetAsPageNum: true
#    rowBoundsWithCount: true
#    reasonable: true
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

config:
  pwd: