#定义compose版本
version: "3.0"
services:

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password #解决外部无法访问
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'SuperMan1014998'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_DATABASE: 'intelligence-locker'
      MYSQL_USER: 'wyt'
      MTSQL_PASSWORD: 'wyt'
    networks:
      - wyt-intelligence-locker
    container_name: mysql-5.7

  redis:
    image: redis:6.2.6
    container_name: redis-6.2.6
    ports:
      - 6379:6379
    restart: always
    volumes: # 数据挂载到宿主机
      - /data/redis-app/data:/data:rw # 把持久化数据挂载到宿主机
      - /data/redis-app/redis.conf:/etc/redis/redis.conf:rw #  把redis的配置文件挂载到宿主机
    environment:
      - TZ=Asia/Shanghai # 解决容器时区问题

    command:
      redis-server /etc/redis/redis.conf --requirepass SuperMan1014998
    networks:
      - wyt-intelligence-locker

  intelligence-locker:
    hostname: wyt
    build: ../../java
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - redis
    networks:
      - wyt-intelligence-locker
    container_name: wyt

networks:
  wyt-intelligence-locker:
